# -*- coding: utf-8 -*-
"""autosklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aG8rEYO9Py-VEXlMdAHRpg7WtJvEDktv
"""

!apt-get install swig -y

!pip install Cython numpy

!pip install auto-sklearn --upgrade

!pip install liac-arff

!pip install dask

!pip install distribution

!pip install dask distributed --upgrade

pip install sklearn --upgrade

import autosklearn.classification

import sklearn.model_selection as cv

import sklearn.datasets

import sklearn.metrics

X, y = sklearn.datasets.load_digits(return_X_y=True)

X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, random_state=1)

automl = autosklearn.classification.AutoSklearnClassifier()

automl.fit(X_train, y_train)

y_hat = automl.predict(X_test)

print("Accuracy score", sklearn.metrics.accuracy_score(y_test, y_hat))

from auto-sklearn.experimental.askl2 import Auto-sklearn2Classifier