# -*- coding: utf-8 -*-
"""AutoKeras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A26ypCxFp_BbPo-B15i9O92yWnWhMeTt
"""

!pip install autokeras

!pip install git+https://github.com/keras-team/keras-tuner.git@1.0.2

!pip install tensorflow

import tensorflow as tf

from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

print(x_train.shape)

print(y_train.shape)

print(y_train[:3])

!pip install --upgrade keras-tuner

import autokeras as ak

clf = ak.ImageClassifier(overwrite=True, max_trials=1)

clf.fit(x_train, y_train, epochs=10)

print(x_test)

predicted_y = clf.predict(x_test)

print(predicted_y)

print(clf.evaluate(x_test, y_test))

model = clf.export_model()

print(type(model))

try: 
    model.save("model_autokeras", save_format="tf")
except:
    model.save("model_autokeras.h5")

from tensorflow.keras.models import load_model

loaded_model = load_model("model_autokeras", custom_objects = ak.CUSTOM_OBJECTS)

predicted_y = loaded_model.predict(x_test)

print(predicted_y)